const customersData = [
  {
    company: 'Android',
    contact: 'John Hendricks',
    telephone: '647-223-3345',
    city: 'Riverview',
    province: 'New Brunswick',
    country: 'Canada',
    address: '32 Harrison Ave',
    postal: 'E1B 6P3',
    employees: 19,
  },
  {
    company: 'Apple',
    contact: 'Bobby Jimmy',
    telephone: '416-807-1366',
    city: 'Lac-Saint-Charles',
    province: 'Quebec',
    country: 'Canada',
    address: '652 South Bear Hill St',
    postal: 'G3G 3B6',
    employees: 5,
  },
  {
    company: 'Amazon',
    contact: 'Dylan Chance',
    telephone: '905-786-1432',
    city: 'Lambton',
    province: 'Ontario',
    country: 'Canada',
    address: '6 East Trout Ave',
    postal: 'N0N 8K7',
    employees: 15,
  },
  {
    company: "Mcdonald's",
    contact: 'Mike chambers',
    telephone: '416-345-7564',
    city: 'Swift Current',
    province: 'Saskatchewan',
    country: 'Canada',
    address: '764 Country Club Court',
    postal: 'S9H 0V2',
    employees: 18,
  },
  {
    company: 'Netflix',
    contact: 'Hillary Scott',
    telephone: '647-654-8797',
    city: 'Yarmouth',
    province: 'Nova Scotia',
    country: 'Canada',
    address: '859 Bow Ridge Lane',
    postal: 'B5A 4G2',
    employees: 12,
  },
  {
    company: 'Nvidia',
    contact: 'Mike Dopler',
    telephone: '905-745-6223',
    city: 'Hawkesbury',
    province: 'Ontario',
    country: 'Canada',
    address: '11 Inverness St',
    postal: 'K6A 6Y9',
    employees: 13,
  },
  {
    company: 'Tesla',
    contact: 'Anthony Pinteo',
    telephone: '416-334-5654',
    city: 'Lacombe',
    province: 'Alberta',
    country: 'Canada',
    address: '295 Green Hill Dr',
    postal: 'T4L 8H6',
    employees: 16,
  },
  {
    company: 'Sony',
    contact: 'Jason Perd',
    telephone: '647-567-1243',
    city: 'Kingston',
    province: 'Ontario',
    country: 'Canada',
    address: '407 Queen Dr',
    postal: 'K7K 4X6',
    employees: 9,
  },
  {
    company: 'Facebook',
    contact: 'Patrick Suzy',
    telephone: '905-675-8997',
    city: 'Cedar',
    province: 'British Columbia',
    country: 'Canada',
    address: '54 Country Street',
    postal: 'V9X 4N6',
    employees: 5,
  },
  {
    company: 'Adobe',
    contact: 'David Griffin',
    telephone: '416-546-7854',
    city: 'Burnaby',
    province: 'British Columbia',
    country: 'Canada',
    address: '9244 Pine Street',
    postal: 'V3N 7E1',
    employees: 22,
  },
  {
    company: 'Google',
    contact: 'Tony Price',
    telephone: '647-334-1232',
    city: 'Greely',
    province: 'Ontario',
    country: 'Canada',
    address: '7812 S. Lexington Ave',
    postal: 'K4P 1S1',
    employees: 13,
  },
];

export { customersData };
